apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: example-runner-autoscaler
  namespace: actions-runner-system
spec:
  scaleTargetRef:
    name: example-runner-deployment
  minReplicas: 0
  maxReplicas: 5
  scaleDownDelaySecondsAfterScaleOut: 300  # Set delay to 5 minutes
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames:
        - akaroth/BasePlatform
      scaleUpThreshold: "1"
      scaleDownThreshold: "0"