apiVersion: v1
kind: Secret
metadata:
  name: controller-manager
  namespace: actions-runner-system
type: Opaque
data:
  github_token: Z2hwX2p5d0xVM2NBSEhkWHptQ0w3WXpHTHNzVElzTmwxZzJ4NEFFdA==


kubectl create secret generic controller-manager -n actions-runner-system \
  --from-literal=github_app_id=1057585 \
  --from-literal=github_app_installation_id=57131313 \
  --from-literal=github_app_private_key="$(cat ~/Downloads/arc-self-runners.2024-11-13.private-key.pem)"
