
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example-runner-deployment
  namespace: actions-runner-system
spec:
  template:
    spec:
      repository: akaroth/BasePlatform  # Replace with your GitHub organization
      labels: ["self-hosted", "kubernetes", "actions-runner-controller"]
