version: '3'

tasks:
  render-actions-runner-controller:
    desc: "Download Actions Runner Controller YAML and output to a file"
    vars:
      output_file: '{{.OUTPUT_FILE | default "actions-runner-controller.yaml"}}'
    cmds:
      - |
        curl -sSL https://github.com/actions/actions-runner-controller/releases/latest/download/actions-runner-controller.yaml > {{.output_file}}
    silent: true