version: '3'

tasks:
  render-helm-template:
    desc: "Render Helm chart templates as YAML with custom variables"
    vars:
      release_name: '{{.RELEASE_NAME | default "prometheus"}}'
      chart_name: '{{.CHART_NAME | default "prometheus-community/kube-prometheus-stack"}}'
      chart_version: '{{.CHART_VERSION | default "65.5.1"}}'
      namespace: '{{.NAMESPACE | default "monitoring"}}'
      output_file: '{{.OUTPUT_FILE | default "output.yaml"}}'
    cmds:
      - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      - helm repo update
      - helm template {{.release_name}} {{.chart_name}} --namespace {{.namespace}} --version {{.chart_version}} > {{.output_file}}
    silent: true