name: Test Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # This targets your self-hosted runners
    steps:
      - uses: actions/checkout@v2
      - name: Run a Test Command
        run: echo "Testing Runner scale up"
